# Site
name: "Our learnings"
description: "Things we've learnt, built or solved on our journey so far."
meta_description: "Things we've learnt, built or solved on our journey so far."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
#google_analytics: ''
#disqus: ''
#mailchimp-list: ''

# Authors
authors:
  nick:
    name: Nick
    display_name: Nick
    #gravatar: 
    email: hello@meanlabs.io
    web: https://meanlabs.io
    #twitter: 
    #description: ""

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge