# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mean Labs Learnings
email: hello@meanlabs.io
description: >
  Things we've learnt, built or solved in our journey
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://meanlabs.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Nick'
bio: >
  TBD
#author_image: "/assets/images/author.jpg"
#twitter_username: jekyllrb
github_username:  nhoughto

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
